### ISSUE TITLE
Auth-Flow Discussion

### ISSUE THREAD

**Issue by omansfeld** [HealthPatterns/HealthPatterns#108]
# Final Auth-Flow
## Considerations
- we open a legal can of worms by saving any personalized data ("Personenbezogene Daten")
- this includes (obviously) email, but can also include usernames that can be freely decided by the user, because they may use their real name, or a nickname that is used elsewhere which makes them identifiable
-> therefore we will try to remain 100% anonymous

- without email we can't provide the usual flow of `create account > email verification > login > reset/forgot password email`
-> we can't save ourselfes from account-creation-spam with email verification
-> users can't reset passwords

## Proposed solution
- account registration requires a captcha
- we generate usernames
- we provide a PUK for password resets
- configure CORS (& nginx) to block user generation by just sending an api call with a password

## Implementation Details
- Password strength and captcha are handled at the frontend
- [OWASP password strength guidelines](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#implement-proper-password-strength-controls)
### API surface
`/api/auth/register`:
takes: password
returns: username, puk, access token

`/api/auth/login`:
takes: form data with `username` and `password`
returns: access token

### for the future:
`/api/auth/refresh`:
for generating a new access token via refresh token
implementation details tbd

`/api/auth/logout`:
for logging out/revoking refresh token
implementation details tbd, only matters once refresh token is implemented

`/api/auth/reset`:
for resetting password/account recovery
takes: username, puk, new password
returns: access token

# Tasks
*you can convert the tasks below to issues by pressing the button that appears when hovering the task*
## Backend
- [x] #109
- [x] #110
- [x] #111
- [ ] implement refresh tokens
- [ ] implement logout functionality
- [x] implement password change functionality
- [ ] #122
- [ ] #123

## Frontend
 - [x] #116
 - [ ] captcha for registration page -> #116
 - [x] #119
 - [x] #118
 - [x] #115
 - [ ] #117
